package Fedora::App::Updates::Model::Updates;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Fedora::App::Updates::Schema',
    
    connect_info => {
        dsn      => 'dbi:mysql:mysql_ssl=1;dbname=fedora;hostname=172.16.42.70',
        user     => 'XXXXX',
        password => 'XXXXX',
    }
);

=head1 NAME

Fedora::App::Updates::Model::Updates - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Fedora::App::Updates>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Fedora::App::Updates::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 AUTHOR

Chris Weyl

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
