package Fedora::App::Updates::Model::Updates;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Fedora::App::Updates::Schema',

    connect_info => {
        dsn      => 'dbi:mysql:mysql_ssl=1;dbname=fedora;hostname=172.16.42.70',
        user     => 'XXXXX',
        password => 'XXXXX',
    }
);

=head1 NAME

Fedora::App::Updates::Model::Updates - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Fedora::App::Updates>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Fedora::App::Updates::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 AUTHOR

Chris Weyl

=head1 LICENCE AND COPYRIGHT

Copyright (c) 2008, Chris Weyl <cweyl@alumni.drew.edu>

This library is free software; you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation; either version 2.1 of the License, or (at your option)
any later version.

This library is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
OR A PARTICULAR PURPOSE.

See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this library; if not, write to the

    Free Software Foundation, Inc.,
    59 Temple Place, Suite 330,
    Boston, MA  02111-1307 USA

=cut

1;
